import type { AccountDef } from "./types";

/**
 * Master multifamily chart of accounts.
 * Numbered practical CoA used as the template cloned onto every entity.
 * Asset management fees (6310) sit BELOW NOI — locked Phase A policy.
 */
export const MASTER_COA: AccountDef[] = [
  {
    code: "1010",
    name: "Cash — Operating",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: true,
    reportGroup: "cash",
    sortOrder: 1010,
    cashFlowClass: "NONE",
  },
  {
    code: "1020",
    name: "Cash — Replacement Reserve",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: true,
    reportGroup: "cash",
    sortOrder: 1020,
    cashFlowClass: "NONE",
  },
  {
    code: "1030",
    name: "Cash — Escrow / Impound",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: true,
    reportGroup: "cash",
    sortOrder: 1030,
    cashFlowClass: "NONE",
  },
  {
    code: "1040",
    name: "Cash — Security Deposits",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: true,
    reportGroup: "cash",
    sortOrder: 1040,
    cashFlowClass: "NONE",
  },
  {
    code: "1110",
    name: "Accounts Receivable — Tenant",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ar",
    sortOrder: 1110,
    cashFlowClass: "OPERATING",
  },
  {
    code: "1190",
    name: "Allowance for Doubtful Accounts",
    type: "ASSET",
    normalBalance: "CREDIT",
    isContra: true,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ar",
    sortOrder: 1190,
    cashFlowClass: "OPERATING",
  },
  {
    code: "1210",
    name: "Prepaid Expenses",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "prepaid",
    sortOrder: 1210,
    cashFlowClass: "OPERATING",
  },
  {
    code: "1310",
    name: "Due from Related Parties",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ic_from",
    sortOrder: 1310,
    cashFlowClass: "OPERATING",
  },
  {
    code: "1350",
    name: "Investment in Subsidiaries",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "investment",
    sortOrder: 1350,
    cashFlowClass: "INVESTING",
  },
  {
    code: "1410",
    name: "Land",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ppe",
    sortOrder: 1410,
    cashFlowClass: "INVESTING",
  },
  {
    code: "1420",
    name: "Building",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ppe",
    sortOrder: 1420,
    cashFlowClass: "INVESTING",
  },
  {
    code: "1430",
    name: "Building Improvements",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ppe",
    sortOrder: 1430,
    cashFlowClass: "INVESTING",
  },
  {
    code: "1440",
    name: "Site Improvements",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ppe",
    sortOrder: 1440,
    cashFlowClass: "INVESTING",
  },
  {
    code: "1450",
    name: "Furniture, Fixtures & Equipment",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ppe",
    sortOrder: 1450,
    cashFlowClass: "INVESTING",
  },
  {
    code: "1460",
    name: "Construction in Progress",
    type: "ASSET",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "cip",
    sortOrder: 1460,
    cashFlowClass: "INVESTING",
  },
  {
    code: "1490",
    name: "Accumulated Depreciation",
    type: "ASSET",
    normalBalance: "CREDIT",
    isContra: true,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ppe",
    sortOrder: 1490,
    cashFlowClass: "NONE",
  },
  {
    code: "2010",
    name: "Accounts Payable",
    type: "LIABILITY",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ap",
    sortOrder: 2010,
    cashFlowClass: "OPERATING",
  },
  {
    code: "2020",
    name: "Accrued Expenses",
    type: "LIABILITY",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "accrual",
    sortOrder: 2020,
    cashFlowClass: "OPERATING",
  },
  {
    code: "2040",
    name: "Prepaid Rent / Unearned Revenue",
    type: "LIABILITY",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "prepaid_rent",
    sortOrder: 2040,
    cashFlowClass: "OPERATING",
  },
  {
    code: "2050",
    name: "Tenant Security Deposits",
    type: "LIABILITY",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "deposits",
    sortOrder: 2050,
    cashFlowClass: "OPERATING",
  },
  {
    code: "2110",
    name: "Mortgage Payable — Current",
    type: "LIABILITY",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "debt_current",
    sortOrder: 2110,
    cashFlowClass: "FINANCING",
  },
  {
    code: "2210",
    name: "Mortgage Payable — Long Term",
    type: "LIABILITY",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "debt_lt",
    sortOrder: 2210,
    cashFlowClass: "FINANCING",
  },
  {
    code: "2310",
    name: "Due to Related Parties",
    type: "LIABILITY",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ic_to",
    sortOrder: 2310,
    cashFlowClass: "OPERATING",
  },
  {
    code: "3010",
    name: "Members' Contributions",
    type: "EQUITY",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "contrib",
    sortOrder: 3010,
    cashFlowClass: "FINANCING",
  },
  {
    code: "3020",
    name: "Members' Distributions",
    type: "EQUITY",
    normalBalance: "DEBIT",
    isContra: true,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "distrib",
    sortOrder: 3020,
    cashFlowClass: "FINANCING",
  },
  {
    code: "3100",
    name: "Retained Earnings",
    type: "EQUITY",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "re",
    sortOrder: 3100,
    cashFlowClass: "NONE",
  },
  {
    code: "3900",
    name: "Current Year Earnings (close)",
    type: "EQUITY",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "ni_close",
    sortOrder: 3900,
    cashFlowClass: "NONE",
  },
  {
    code: "4010",
    name: "Gross Potential Rent",
    type: "REVENUE",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "gpr",
    sortOrder: 4010,
    cashFlowClass: "OPERATING",
  },
  {
    code: "4020",
    name: "Vacancy Loss",
    type: "REVENUE",
    normalBalance: "DEBIT",
    isContra: true,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "vacancy",
    sortOrder: 4020,
    cashFlowClass: "OPERATING",
  },
  {
    code: "4030",
    name: "Concessions / Free Rent",
    type: "REVENUE",
    normalBalance: "DEBIT",
    isContra: true,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "concessions",
    sortOrder: 4030,
    cashFlowClass: "OPERATING",
  },
  {
    code: "4100",
    name: "Other Income",
    type: "REVENUE",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "other_income",
    sortOrder: 4100,
    cashFlowClass: "OPERATING",
  },
  {
    code: "7010",
    name: "Asset Management Fee Income",
    type: "REVENUE",
    normalBalance: "CREDIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "am_income",
    sortOrder: 7010,
    cashFlowClass: "OPERATING",
  },
  {
    code: "5110",
    name: "Payroll",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "opex_payroll",
    sortOrder: 5110,
    cashFlowClass: "OPERATING",
  },
  {
    code: "5210",
    name: "Repairs & Maintenance",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "opex_rm",
    sortOrder: 5210,
    cashFlowClass: "OPERATING",
  },
  {
    code: "5310",
    name: "Utilities",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "opex_util",
    sortOrder: 5310,
    cashFlowClass: "OPERATING",
  },
  {
    code: "5410",
    name: "Contract Services",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "opex_contracts",
    sortOrder: 5410,
    cashFlowClass: "OPERATING",
  },
  {
    code: "5510",
    name: "Marketing",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "opex_marketing",
    sortOrder: 5510,
    cashFlowClass: "OPERATING",
  },
  {
    code: "5610",
    name: "Administrative",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "opex_admin",
    sortOrder: 5610,
    cashFlowClass: "OPERATING",
  },
  {
    code: "5710",
    name: "Insurance",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "opex_ins",
    sortOrder: 5710,
    cashFlowClass: "OPERATING",
  },
  {
    code: "5810",
    name: "Real Estate Taxes",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "opex_tax",
    sortOrder: 5810,
    cashFlowClass: "OPERATING",
  },
  {
    code: "5910",
    name: "Property Management Fees",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "opex_pm",
    sortOrder: 5910,
    cashFlowClass: "OPERATING",
  },
  {
    code: "5990",
    name: "Other Operating Expenses",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: false,
    isCash: false,
    reportGroup: "opex_other",
    sortOrder: 5990,
    cashFlowClass: "OPERATING",
  },
  {
    code: "6110",
    name: "Interest Expense",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: true,
    isCash: false,
    reportGroup: "interest",
    sortOrder: 6110,
    cashFlowClass: "OPERATING",
  },
  {
    code: "6210",
    name: "Depreciation Expense",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: true,
    isCash: false,
    reportGroup: "depreciation",
    sortOrder: 6210,
    cashFlowClass: "NONE",
  },
  {
    code: "6310",
    name: "Asset Management Fees",
    type: "EXPENSE",
    normalBalance: "DEBIT",
    isContra: false,
    isBelowNoi: true,
    isCash: false,
    reportGroup: "am_fee",
    sortOrder: 6310,
    cashFlowClass: "OPERATING",
  },
];

export const MASTER_COA_BY_CODE = new Map(MASTER_COA.map((a) => [a.code, a]));

export function cloneMasterCoa(): AccountDef[] {
  return MASTER_COA.map((row) => ({ ...row }));
}
